title: GIZ Tools
email: gizipp.gizipp+tools@gmail.com
description: >-
  Various collection tools for human, web developer or programing. HTML / ERB to Slim Converter

url: 'https://tools.gizipp.com'
permalink: '/:title'
plugins:
  - jekyll-sitemap
